<!--<select>-->
<!--        <option value="#">¿Eres clienta experta?</option>-->
<!--        <option value="">Iniciar session</option>-->
<!--        <option value="">Activa tu cuanta experta</option>-->
<!--        <option value="">¿Que es clienta experta?</option>-->
<!--</select>-->


<div class="client-expert">
    <span>¿Eres clienta experta?</span>
    <ul>
        <li><a href="#">Iniciar session</a></li>
        <li><a href="#">Activa tu cuanta experta</a></li>
        <li><a href="#">¿Que es clienta experta?</a></li>
    </ul>
</div>